spring.datasource.url=jdbc:postgresql://localhost:5432/CinemaTick_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-psql=true

logging.level.root=INFO
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl.auto=update
spring.jpa.properties.hibernate.show.psql=true
server.port=9090
